security:
    encoders:
        Blog\ModelBundle\Entity\User: plaintext
        Blog\ModelBundle\Entity\Author: plaintext
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:             ROLE_USER
        ROLE_SUPER_ADMIN:       [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: [ 'ROLE_SUPER_ADMIN' ] }
        author:
            entity:
                class: ModelBundle:Author
                property: name
        user:
            entity:
                class: ModelBundle:User
                property: email
        admin:
            chain:
                providers: [in_memory, author]

    firewalls:

         dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

         admin_area:
            pattern: ^/admin
            anonymous: ~
            provider: admin
            form_login:
                login_path: blog_admin_security_login
                check_path: blog_admin_security_logincheck
            logout:
                path: blog_admin_security_logout
                target: /admin/post

         frontend_area:
            pattern: ^/
            anonymous: ~
            provider: user
            form_login:
                login_path: blog_core_security_login
                check_path: blog_core_security_logincheck
            logout:
                path: blog_core_security_logout
                target: blog_core_post_index

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/en/, roles: ROLE_USER }
