<?php

namespace Blog\ModelBundle\Repository;

use Blog\ModelBundle\Entity\Post;
use Blog\ModelBundle\Entity\Tag;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * Find the latest posts
     *
     * @param $num
     * @return array
     */

    public function findLatest($num)
    {
        $qb = $this->getQueryBuilder()
            ->orderBy('p.createdAt', 'desc')
            ->setMaxResults($num);

        return $qb->getQuery()->getResult();
    }

    /**
     * Find the first post
     *
     * @return Post
     */
    public function findFirst()
    {
        $qb = $this->getQueryBuilder()
            ->orderBy('p.id', 'asc')
            ->setMaxResults(1);

        return $qb->getQuery()->getSingleResult();
    }

    /**
     * Find all post to tag
     *
     * @param Tag $tag
     * @return array
     */
    public function findPostToTag($tag)
    {
        $qb = $this->getQueryBuilder();

        $qb->join('p.tags', 't', 'WITH', $qb->expr()->in('t.id', $tag->getId()));

        return $qb->getQuery()->getResult();
    }

    /**
     * Get a query builder
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();

        $qb = $em->getRepository('ModelBundle:Post')
            ->createQueryBuilder('p');

        return $qb;
    }
}
