<?php

namespace Blog\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getTagsWhichHasLeastOnePost()
    {
        $qb = $this->getQueryBuilder();

        $qb->select('t')
            ->innerJoin('t.posts', 'p')
            ->groupBy('t.id');

        return $qb->getQuery()->getResult();
    }


    /**
     * Get a query builder
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();

        $qb = $em->getRepository('ModelBundle:Tag')
            ->createQueryBuilder('t');

        return $qb;
    }
}
