parameters:
    author_manager.class: Blog\CoreBundle\Services\AuthorManager
    post_manager_class: Blog\CoreBundle\Services\PostManager
    configuration_class: Blog\CoreBundle\Services\Configuration
services:
    author_manager:
        class: %author_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
    post_manager:
        class: %post_manager_class%
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory
    configuration:
        class: %configuration_class%
        arguments:
            - @doctrine.orm.entity_manager